version: '3.2'
services:
  frontend:
    image: node:14-slim
    command: bash -c 'node credits/src/main'
    ports:
      - "80:3000"
    working_dir: /app
    user: "1000:1000"
    volumes:
      - type: "bind"
        source: ./dist
        target: /app